### ISSUE TITLE
Uploading multiple files

### ISSUE THREAD

**Issue by PatrikTrefil** [MrFlynn/upload-to-netlify-action#17]
The tutorial for uploading multiple files with this action which is included in the readme is incorrect.

Tutorial suggests:

```yaml
source-file: |
            src/prace.pdf
            src/abstrakt.pdf
```

This fails with the following error: `Error opening source file : open : no such file or directory`.
The reason is that the action is confused because of the trailing newline which is added using the pipe `|` syntax.

It is necessary to either modify the program to ignore the trailing newline or update the documentation to the following (note the `|-` syntax):

```yaml
source-file: |-
            src/prace.pdf
            src/abstrakt.pdf
```

I suggest fixing the documentation and ideally using the standard yaml list syntax in future versions. I believe lists are the better choice in this case.

**Comment by MrFlynn** [comment]
Hi, thanks for catching this issue. I've gone ahead and updated the example in the README to ignore trailing newlines.

Unfortunately Github actions doesn't support list inputs, so you have to approximate it using multi-line inputs like this.
